//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package net.monoboy.br;

import android.content.Context;
import android.content.Intent;
import android.telephony.TelephonyManager;
import android.view.WindowManager;

public final class PhoneStateReceiver_
    extends PhoneStateReceiver
{

    private Context context_;

    private void init_() {
        windowManager = ((WindowManager) context_.getSystemService(Context.WINDOW_SERVICE));
        telephonyManager = ((TelephonyManager) context_.getSystemService(Context.TELEPHONY_SERVICE));
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        context_ = context;
        init_();
        super.onReceive(context, intent);
    }

}
