//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package net.monoboy.br;

import android.content.Context;
import android.content.Intent;

public final class StartupReceiver_
    extends StartupReceiver
{

    private Context context_;

    private void init_() {
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        context_ = context;
        init_();
        super.onReceive(context, intent);
    }

}
