//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package net.monoboy.test.br;

import android.content.Context;
import android.content.Intent;
import android.os.Handler;
import android.util.Log;

public final class SmsReceiver_
    extends SmsReceiver
{

    private Context context_;
    private Handler handler_ = new Handler();

    private void init_() {
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        context_ = context;
        init_();
        super.onReceive(context, intent);
    }

    @Override
    public void showSMS(final Context context, final String messages) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SmsReceiver_.super.showSMS(context, messages);
                } catch (RuntimeException e) {
                    Log.e("SmsReceiver_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
