//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package net.monoboy.service;

import android.content.Context;
import android.content.Intent;

public final class StartupService_
    extends StartupService
{


    private void init_() {
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    public static StartupService_.IntentBuilder_ intent(Context context) {
        return new StartupService_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, StartupService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public StartupService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startService(intent_);
        }

    }

}
